import { describe, expect, test } from "bun:test";
import {
  parseBranchSummary,
  parseGeneratedAttributes,
  parseStatusSummary,
  readDiffSummary,
  statusLabel,
} from "./git-diff";

describe("git diff summary parsing", () => {
  test("labels git statuses", () => {
    expect(statusLabel("A", "staged")).toBe("added");
    expect(statusLabel("D", "unstaged")).toBe("deleted");
    expect(statusLabel("M", "branch")).toBe("modified");
    expect(statusLabel("M", "untracked")).toBe("untracked");
    expect(statusLabel("M", "conflicted")).toBe("conflicted");
  });

  test("parses working tree porcelain status", () => {
    const entries = parseStatusSummary(
      [
        " M src/changed.ts",
        "A  src/staged.ts",
        "?? src/new.ts",
        "UU src/conflict.ts",
        "R  src/old.ts -> src/renamed.ts",
      ].join("\n"),
    );

    expect(entries).toEqual([
      {
        path: "src/changed.ts",
        kind: "unstaged",
        status: "modified",
      },
      {
        path: "src/conflict.ts",
        kind: "conflicted",
        status: "conflicted",
      },
      {
        path: "src/new.ts",
        kind: "untracked",
        status: "untracked",
      },
      {
        path: "src/renamed.ts",
        old_path: "src/old.ts",
        kind: "staged",
        status: "renamed",
      },
      {
        path: "src/staged.ts",
        kind: "staged",
        status: "added",
      },
    ]);
  });

  test("parses branch name-status output", () => {
    expect(parseBranchSummary("M\tapp.ts\nR100\told.ts\tnew.ts\n")).toEqual([
      {
        path: "app.ts",
        old_path: undefined,
        kind: "branch",
        status: "modified",
      },
      {
        path: "new.ts",
        old_path: "old.ts",
        kind: "branch",
        status: "renamed",
      },
    ]);
  });

  test("recognizes files marked generated by Git attributes", () => {
    const output = [
      "dist/app.js",
      "linguist-generated",
      "true",
      "src/app.ts",
      "linguist-generated",
      "unspecified",
      "vendor/schema.ts",
      "linguist-generated",
      "set",
      "",
    ].join("\0");

    expect(Array.from(parseGeneratedAttributes(output))).toEqual([
      "dist/app.js",
      "vendor/schema.ts",
    ]);
  });

  test("adds Git generated markers to diff summary entries", async () => {
    const commands: string[] = [];
    const summary = await readDiffSummary({
      workspaceId: "workspace",
      workspace: { label: "Repo" },
      root: "/repo",
      params: { mode: "working" },
      shQuote: (value) => `'${value}'`,
      runProcessWithCodeTimeout: async (argv) => {
        const command = argv.join(" ");
        commands.push(command);
        if (command.includes("status --porcelain")) {
          return {
            code: 0,
            stdout: "?? dist/app.js\n M src/app.ts\n",
            stderr: "",
          };
        }
        if (command.includes("check-attr")) {
          return {
            code: 0,
            stdout: [
              "dist/app.js",
              "linguist-generated",
              "true",
              "src/app.ts",
              "linguist-generated",
              "unspecified",
              "",
            ].join("\0"),
            stderr: "",
          };
        }
        if (command.includes("--no-index")) {
          return {
            code: 1,
            stdout: "1200\t0\tdist/app.js\n",
            stderr: "",
          };
        }
        if (command.includes("diff --numstat")) {
          return {
            code: 0,
            stdout: "10\t2\tsrc/app.ts\n",
            stderr: "",
          };
        }
        return { code: 0, stdout: "", stderr: "" };
      },
    });

    expect(summary.entries).toContainEqual({
      path: "dist/app.js",
      kind: "untracked",
      status: "untracked",
      additions: 1200,
      deletions: 0,
      generated: true,
    });
    expect(commands.some((command) => command.includes("check-attr -z"))).toBe(
      true,
    );
  });
});
