import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, resolve } from "node:path";
import {
  DEFAULT_SERVICE_ENV_FILE,
  escapeSystemdExecPath,
  GENERATED_MARKER,
  renderLaunchdService,
  renderSystemdService,
  resolveServicePaths,
  resolveServicePlatform,
  SERVICE_LABEL,
  type ServicePlatform,
} from "./service-definitions";
import { defaultAuthTokenPath, loadOrCreateAuthToken } from "./auth-token";
import {
  browserUrlFor,
  getLanIPs,
  isAnyHost,
  withLoginToken,
} from "./server-config";

type ServiceAction = "install" | "uninstall" | "status" | "restart" | "reload";

interface ServiceRuntime {
  platform: string;
  homeDir: string;
  execPath: string;
  argv: string[];
  uid?: number;
}

type RunCommand = (argv: string[], options?: { quiet?: boolean }) => number;

interface ServiceCommandDependencies {
  runtime?: ServiceRuntime;
  runCommand?: RunCommand;
  getLanIPs?: () => string[];
  log?: (message: string) => void;
  error?: (message: string) => void;
}

interface ParsedServiceCommand {
  action: ServiceAction | "help";
  force: boolean;
}

function parseServiceCommand(args: string[]): ParsedServiceCommand | null {
  if (args[0] !== "service") return null;
  const tail = args.slice(1);
  if (
    tail.length === 0 ||
    tail[0] === "help" ||
    tail.includes("--help") ||
    tail.includes("-h")
  ) {
    return { action: "help", force: false };
  }

  const action = tail[0];
  if (
    !["install", "uninstall", "status", "restart", "reload"].includes(action)
  ) {
    throw new Error(`unknown service action: ${action}`);
  }
  const options = tail.slice(1);
  const unknown = options.filter((option) => option !== "--force");
  if (unknown.length > 0) {
    throw new Error(`unknown service option: ${unknown[0]}`);
  }
  if (options.includes("--force") && action !== "install") {
    throw new Error("--force is only valid with `service install`");
  }
  return {
    action: action as ServiceAction,
    force: options.includes("--force"),
  };
}

function serviceHelp(): string {
  return `Manage herdr-gui as a user service.

Usage:
  herdr-gui service install [--force]
  herdr-gui service status
  herdr-gui service restart
  herdr-gui service reload
  herdr-gui service uninstall

Linux uses a systemd user service. macOS uses a launchd LaunchAgent.
New services listen on 0.0.0.0 and use a generated login token by default.
Install prints tokenized login URLs, preserves
~/.config/herdr-gui/herdr-gui.env, and starts the service.
Reload re-reads the service definition and restarts the process.
Use --force only to replace an existing service definition not generated by
herdr-gui. Uninstall preserves the environment file.
`;
}

function defaultRunCommand(
  argv: string[],
  options: { quiet?: boolean } = {},
): number {
  const result = Bun.spawnSync(argv, {
    stdin: "inherit",
    stdout: options.quiet ? "ignore" : "inherit",
    stderr: options.quiet ? "ignore" : "inherit",
  });
  return result.exitCode ?? 1;
}

function ensureStandaloneBinary(runtime: ServiceRuntime): string {
  const invoked = runtime.argv[1] ?? "";
  if (
    basename(runtime.execPath) === "bun" ||
    invoked.endsWith("src/index.ts")
  ) {
    throw new Error("service install requires the standalone herdr-gui binary");
  }
  return resolve(runtime.execPath);
}

function assertServiceDefinitionWritable(path: string, force: boolean) {
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    if (!existing.includes(GENERATED_MARKER) && !force) {
      throw new Error(
        `${path} was not generated by herdr-gui; rerun with --force to replace it`,
      );
    }
  }
}

function commandContainsArgument(command: string, argument: string): boolean {
  let offset = 0;
  while (offset < command.length) {
    const index = command.indexOf(argument, offset);
    if (index < 0) return false;
    const before = index === 0 ? "" : command[index - 1];
    const afterIndex = index + argument.length;
    const after = afterIndex >= command.length ? "" : command[afterIndex];
    const hasStartBoundary = before === "" || /\s|["']/.test(before);
    const hasEndBoundary = after === "" || /\s|["']/.test(after);
    if (hasStartBoundary && hasEndBoundary) return true;
    offset = index + argument.length;
  }
  return false;
}

function preservedSystemdExecStart(
  definitionPath: string,
  binaryPath: string,
): string | undefined {
  if (!existsSync(definitionPath)) return undefined;
  const contents = readFileSync(definitionPath, "utf8");
  if (!contents.includes(GENERATED_MARKER)) return undefined;

  const commands = contents
    .split(/\r?\n/)
    .filter((line) => line.startsWith("ExecStart="))
    .map((line) => line.slice("ExecStart=".length).trim())
    .filter(Boolean);
  if (commands.length !== 1) return undefined;

  const command = commands[0];
  const directCommands = new Set([
    binaryPath,
    escapeSystemdExecPath(binaryPath),
    // Recognize the quoted form emitted by herdr-gui <= 0.2.20 so reinstall
    // migrates it instead of treating it as a custom wrapper command.
    `"${binaryPath
      .replaceAll("\\", "\\\\")
      .replaceAll('"', '\\"')
      .replaceAll("%", "%%")}"`,
  ]);
  if (directCommands.has(command)) return undefined;

  // Keep an intentional supervisor wrapper only when it still launches the
  // exact binary being installed. Stale or unrelated commands are replaced.
  return commandContainsArgument(command, binaryPath) ? command : undefined;
}

function writeServiceDefinition(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true });
  const temporaryPath = `${path}.tmp-${process.pid}`;
  try {
    writeFileSync(temporaryPath, content, { mode: 0o644 });
    renameSync(temporaryPath, path);
  } finally {
    rmSync(temporaryPath, { force: true });
  }
}

function ensureEnvironmentFile(path: string): boolean {
  mkdirSync(dirname(path), { recursive: true });
  const created = !existsSync(path);
  if (created) writeFileSync(path, DEFAULT_SERVICE_ENV_FILE, { mode: 0o600 });
  chmodSync(path, 0o600);
  return created;
}

function readEnvironmentValue(
  contents: string,
  name: string,
): string | undefined {
  let value: string | undefined;
  for (const line of contents.split(/\r?\n/)) {
    const match = line.match(
      new RegExp(`^\\s*(?:export\\s+)?${name}\\s*=\\s*(.*?)\\s*$`),
    );
    if (!match) continue;
    const rawValue = match[1] ?? "";
    const quote = rawValue[0];
    value =
      rawValue.length >= 2 &&
      (quote === "'" || quote === '"') &&
      rawValue.at(-1) === quote
        ? rawValue.slice(1, -1)
        : rawValue;
  }
  return value;
}

interface ServiceAccess {
  host: string;
  port: number;
  token?: string;
  tokenPath?: string;
  usesFixedPassword: boolean;
}

function prepareServiceAccess(
  configPath: string,
  homeDir: string,
): ServiceAccess {
  const contents = readFileSync(configPath, "utf8");
  const host = readEnvironmentValue(contents, "HOST") || "127.0.0.1";
  const configuredPort = readEnvironmentValue(contents, "PORT");
  const port = Number(configuredPort || 8787);
  if (!Number.isInteger(port) || port < 1 || port > 65_535) {
    throw new Error(`invalid PORT in ${configPath}: ${configuredPort}`);
  }

  const password = readEnvironmentValue(contents, "HERDR_GUI_PASSWORD") ?? "";
  const usesFixedPassword = password.length > 0;
  if (
    usesFixedPassword ||
    host === "127.0.0.1" ||
    host === "localhost" ||
    host === "::1"
  ) {
    return { host, port, usesFixedPassword };
  }

  const tokenPath = defaultAuthTokenPath(homeDir);
  return {
    host,
    port,
    token: loadOrCreateAuthToken(tokenPath),
    tokenPath,
    usesFixedPassword,
  };
}

function printServiceAccess(
  access: ServiceAccess,
  resolveLanIPs: () => string[],
  log: (message: string) => void,
) {
  if (access.usesFixedPassword) {
    log("Authentication: fixed password from the service config");
    log(`Open: ${browserUrlFor(access.host, access.port)}`);
    return;
  }
  if (!access.token) {
    log(`Open: ${browserUrlFor(access.host, access.port)} (local access)`);
    return;
  }

  log(`Login token: ${access.token}`);
  log(`Token file: ${access.tokenPath}`);
  log(
    `Open: ${withLoginToken(
      browserUrlFor(access.host, access.port),
      access.token,
    )}`,
  );
  if (isAnyHost(access.host)) {
    for (const ip of resolveLanIPs()) {
      log(
        `LAN: ${withLoginToken(`http://${ip}:${access.port}`, access.token)}`,
      );
    }
  }
}

function installService(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  force: boolean,
  runCommand: RunCommand,
  resolveLanIPs: () => string[],
  log: (message: string) => void,
): number {
  const binaryPath = ensureStandaloneBinary(runtime);
  if (platform === "launchd" && runtime.uid === undefined) {
    throw new Error("cannot determine the current user id for launchd");
  }
  const paths = resolveServicePaths(platform, runtime.homeDir);
  assertServiceDefinitionWritable(paths.definition, force);
  const environmentCreated = ensureEnvironmentFile(paths.config);
  const access = prepareServiceAccess(paths.config, runtime.homeDir);
  if (paths.stdoutLog) mkdirSync(dirname(paths.stdoutLog), { recursive: true });
  const customSystemdExecStart =
    platform === "systemd"
      ? preservedSystemdExecStart(paths.definition, binaryPath)
      : undefined;
  const definition =
    platform === "systemd"
      ? renderSystemdService(binaryPath, paths.config, customSystemdExecStart)
      : renderLaunchdService(binaryPath, paths);
  writeServiceDefinition(paths.definition, definition);

  let code: number;
  if (platform === "systemd") {
    code = runCommand(["systemctl", "--user", "daemon-reload"]);
    if (code === 0) {
      code = runCommand(["systemctl", "--user", "enable", "herdr-gui.service"]);
    }
    if (code === 0) {
      // `enable --now` does not restart an already-active service after its
      // definition changes. An explicit restart makes reinstall deterministic.
      code = runCommand([
        "systemctl",
        "--user",
        "restart",
        "herdr-gui.service",
      ]);
    }
  } else {
    const domain = `gui/${runtime.uid}`;
    const service = `${domain}/${SERVICE_LABEL}`;
    const loaded =
      runCommand(["launchctl", "print", service], { quiet: true }) === 0;
    if (loaded) {
      code = runCommand(["launchctl", "bootout", service]);
    } else {
      code = 0;
    }
    if (code === 0) {
      code = runCommand(["launchctl", "bootstrap", domain, paths.definition]);
    }
  }

  if (code === 0) {
    log(`Installed ${platform} service: ${paths.definition}`);
    log(
      environmentCreated
        ? `Created service config: ${paths.config}`
        : `Preserved service config: ${paths.config}`,
    );
    if (customSystemdExecStart) {
      log(`Preserved custom ExecStart: ${customSystemdExecStart}`);
    }
    printServiceAccess(access, resolveLanIPs, log);
  }
  return code;
}

function uninstallService(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  runCommand: RunCommand,
  log: (message: string) => void,
): number {
  const paths = resolveServicePaths(platform, runtime.homeDir);
  if (!existsSync(paths.definition)) {
    log(`No managed ${platform} service found: ${paths.definition}`);
    log(`Preserved service config: ${paths.config}`);
    return 0;
  }
  if (!readFileSync(paths.definition, "utf8").includes(GENERATED_MARKER)) {
    throw new Error(
      `${paths.definition} was not generated by herdr-gui and will not be removed`,
    );
  }
  if (platform === "systemd") {
    const stopCode = runCommand([
      "systemctl",
      "--user",
      "disable",
      "--now",
      "herdr-gui.service",
    ]);
    if (stopCode !== 0) return stopCode;
    rmSync(paths.definition, { force: true });
    const code = runCommand(["systemctl", "--user", "daemon-reload"]);
    if (code !== 0) return code;
  } else {
    if (runtime.uid === undefined) {
      throw new Error("cannot determine the current user id for launchd");
    }
    const service = `gui/${runtime.uid}/${SERVICE_LABEL}`;
    const loaded =
      runCommand(["launchctl", "print", service], { quiet: true }) === 0;
    if (loaded) {
      const stopCode = runCommand(["launchctl", "bootout", service]);
      if (stopCode !== 0) return stopCode;
    }
    rmSync(paths.definition, { force: true });
  }
  log(`Removed ${platform} service: ${paths.definition}`);
  log(`Preserved service config: ${paths.config}`);
  return 0;
}

function runServiceAction(
  action: Exclude<ServiceAction, "install" | "uninstall">,
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  runCommand: RunCommand,
): number {
  if (action === "reload") {
    const paths = resolveServicePaths(platform, runtime.homeDir);
    if (!existsSync(paths.definition)) {
      throw new Error(
        `cannot reload missing ${platform} service: ${paths.definition}`,
      );
    }
    if (platform === "systemd") {
      const reloadCode = runCommand(["systemctl", "--user", "daemon-reload"]);
      if (reloadCode !== 0) return reloadCode;
      return runCommand([
        "systemctl",
        "--user",
        "restart",
        "herdr-gui.service",
      ]);
    }
    if (runtime.uid === undefined) {
      throw new Error("cannot determine the current user id for launchd");
    }
    const domain = `gui/${runtime.uid}`;
    const service = `${domain}/${SERVICE_LABEL}`;
    const loaded =
      runCommand(["launchctl", "print", service], { quiet: true }) === 0;
    if (loaded) {
      const bootoutCode = runCommand(["launchctl", "bootout", service]);
      if (bootoutCode !== 0) return bootoutCode;
    }
    return runCommand(["launchctl", "bootstrap", domain, paths.definition]);
  }
  if (platform === "systemd") {
    return runCommand(
      action === "status"
        ? ["systemctl", "--user", "--no-pager", "status", "herdr-gui.service"]
        : ["systemctl", "--user", "restart", "herdr-gui.service"],
    );
  }
  if (runtime.uid === undefined) {
    throw new Error("cannot determine the current user id for launchd");
  }
  const service = `gui/${runtime.uid}/${SERVICE_LABEL}`;
  return runCommand(
    action === "status"
      ? ["launchctl", "print", service]
      : ["launchctl", "kickstart", "-k", service],
  );
}

export function runServiceCommand(
  args: string[],
  dependencies: ServiceCommandDependencies = {},
): number | null {
  const log = dependencies.log ?? console.log;
  const error = dependencies.error ?? console.error;
  let command: ParsedServiceCommand | null;
  try {
    command = parseServiceCommand(args);
    if (!command) return null;
    if (command.action === "help") {
      log(serviceHelp());
      return 0;
    }

    const runtime: ServiceRuntime = dependencies.runtime ?? {
      platform: process.platform,
      homeDir: homedir(),
      execPath: process.execPath,
      argv: process.argv,
      uid: process.getuid?.(),
    };
    const platform = resolveServicePlatform(runtime.platform);
    const runCommand = dependencies.runCommand ?? defaultRunCommand;
    if (command.action === "install") {
      return installService(
        platform,
        runtime,
        command.force,
        runCommand,
        dependencies.getLanIPs ?? getLanIPs,
        log,
      );
    }
    if (command.action === "uninstall") {
      return uninstallService(platform, runtime, runCommand, log);
    }
    return runServiceAction(command.action, platform, runtime, runCommand);
  } catch (cause) {
    error(`herdr-gui service: ${(cause as Error).message}`);
    error("Run `herdr-gui service --help` for usage.");
    return 1;
  }
}
