import { describe, expect, test } from "bun:test";
import {
  diffAutoCollapseInfo,
  LARGE_DIFF_CHANGED_LINES,
} from "./diffAutoCollapse";
import type { GitDiffEntry, GitDiffFile } from "../types";

function entry(patch: Partial<GitDiffEntry> = {}): GitDiffEntry {
  return {
    path: "src/app.ts",
    kind: "unstaged",
    status: "modified",
    ...patch,
  };
}

function file(patch: Partial<GitDiffFile> = {}): GitDiffFile {
  return {
    workspace_id: "workspace",
    root: "/repo",
    path: "src/app.ts",
    kind: "unstaged",
    diff: "",
    truncated: false,
    ...patch,
  };
}

describe("diffAutoCollapseInfo", () => {
  test("collapses files marked generated by Git attributes", () => {
    expect(diffAutoCollapseInfo(entry({ generated: true }))).toEqual({
      reason: "generated",
      label: "generated file",
    });
  });

  test("collapses diffs at the large line threshold", () => {
    expect(
      diffAutoCollapseInfo(
        entry({ additions: LARGE_DIFF_CHANGED_LINES - 1, deletions: 1 }),
      ),
    ).toEqual({
      reason: "large",
      label: "1,000 changed lines",
    });
  });

  test("collapses byte-truncated diffs and leaves ordinary diffs open", () => {
    expect(diffAutoCollapseInfo(entry(), file({ truncated: true }))).toEqual({
      reason: "truncated",
      label: "large diff",
    });
    expect(
      diffAutoCollapseInfo(entry({ additions: 20, deletions: 10 }), file()),
    ).toBeNull();
  });
});
